#!/bin/bash

set -e

DATE=$(date +%Y%m%d)
CONFIG_NAME=pablomer
# CONFIG_OVERRIDES="train_steps=1000"
CONFIG_OVERRIDES="train_steps=1000"

# CODE_DIR=/pdo/users/cshallue/git/astronet
CODE_DIR=/pdo/users/pablomer/Astronet-Triage

# Path to TFRecords with soft labels (generated by update_tfrecords_with_predictions.py)
# These should have the _softlabels suffix
DATA_DIR=/pdo/astronet-data/data/tfrecords/oct2025_30minbin_v2
TFRECORD_PREFIX=tfrecords-vetting-v01-tois-triageJs-nocentroid-april2025

# Output directory for trained student model
OUTPUT_DIR=/pdo/astronet-data/models/vetting/experimental/pablomer/oct2025_30minbin_v2/$DATE/student-2k-pretrained/

# Distillation hyperparameterss
SOFT_LABEL_WEIGHT=1.0
HARD_LABEL_WEIGHT=0.1
TEMPERATURE=1.0

# Evaluation datasets (using original TFRecords, not softlabels)
EVAL_DATA_DIR=/pdo/astronet-data/data/tfrecords/oct2025_30minbin_v2
EVAL_TFRECORD_PREFIX=tfrecords-vetting-v01-tois-triageJs-nocentroid-april2025

echo "Training student model with soft labels"
echo "========================================"
echo "Config: $CONFIG_NAME"
echo "Train files: $DATA_DIR/${TFRECORD_PREFIX}-train_softlabels/*"
echo "Output dir: $OUTPUT_DIR"
echo "Soft label weight: $SOFT_LABEL_WEIGHT"
echo "Hard label weight: $HARD_LABEL_WEIGHT"
echo "Temperature: $TEMPERATURE"
echo "========================================"

PYTHONNOUSERSITE=1 \
LD_LIBRARY_PATH=/pdo/users/cshallue/miniconda3/lib:$LD_LIBRARY_PATH \
/pdo/users/cshallue/miniconda3/envs/astronet-gpu/bin/python $CODE_DIR/distillation/train_student.py \
    --model=AstroCNNModelVetting \
    --config_name=$CONFIG_NAME \
    --config_overrides="$CONFIG_OVERRIDES" \
    --model_dir="$OUTPUT_DIR" \
    --train_files="$DATA_DIR/${TFRECORD_PREFIX}-train_softlabels/*" \
    --soft_label_weight=$SOFT_LABEL_WEIGHT \
    --hard_label_weight=$HARD_LABEL_WEIGHT \
    --temperature=$TEMPERATURE \
    --use_binary_loss_for_hard_labels \
    --eval_files="val:$EVAL_DATA_DIR/${EVAL_TFRECORD_PREFIX}-val/*" \
    --eval_files="test:$EVAL_DATA_DIR/${EVAL_TFRECORD_PREFIX}-test/*" \
    --shuffle_buffer_size=25000 \
    --save_format=h5

echo "Student model training complete!"
echo "Model saved to: $OUTPUT_DIR"
